-- =============================================================================
-- oracle_setup.sql
-- Setup complet des tables sources Oracle pour la migration (simulation ERP)
--
-- Usage :
--   docker exec -it oracle-dev sqlplus migration_reader/ReaderPass#2024@//localhost:1521/XEPDB1
--   SQL> @/tmp/oracle_setup.sql
--
-- Ou directement :
--   docker cp scripts/oracle_setup.sql oracle-dev:/tmp/
--   docker exec -it oracle-dev sqlplus migration_reader/ReaderPass#2024@//localhost:1521/XEPDB1 @/tmp/oracle_setup.sql
-- =============================================================================

-- Nettoyage préalable (si re-exécution)
BEGIN
    FOR t IN (SELECT table_name FROM user_tables
              WHERE table_name IN (
                'FACT_TXN','LKP_CONTINENT','LKP_COUNTRY',
                'LKP_REGION','LKP_CITY',
                'LKP_PROD_LINE','LKP_PROD_FAM','DIM_PRODUCT','DIM_CUSTOMER'
              )) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- =============================================================================
-- TABLES LOOKUP — Géographie
-- =============================================================================

CREATE TABLE LKP_CONTINENT (
    CONTINENT_CD  VARCHAR2(2)   NOT NULL,
    CONTINENT_NM  VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_CONTINENT PRIMARY KEY (CONTINENT_CD)
);

CREATE TABLE LKP_COUNTRY (
    COUNTRY_CD    VARCHAR2(3)   NOT NULL,
    COUNTRY_NM    VARCHAR2(200) NOT NULL,
    CONTINENT_CD  VARCHAR2(2),
    CURRENCY_CD   VARCHAR2(3),
    IS_EU_FLG     NUMBER(1)     DEFAULT 0,
    ACTIVE_FLG    NUMBER(1)     DEFAULT 1,
    CONSTRAINT PK_COUNTRY PRIMARY KEY (COUNTRY_CD),
    CONSTRAINT FK_COUNTRY_CONT FOREIGN KEY (CONTINENT_CD) REFERENCES LKP_CONTINENT(CONTINENT_CD)
);

CREATE TABLE LKP_REGION (
    REGION_CD     VARCHAR2(10)  NOT NULL,
    REGION_NM     VARCHAR2(200) NOT NULL,
    COUNTRY_CD    VARCHAR2(3),
    CONSTRAINT PK_REGION PRIMARY KEY (REGION_CD),
    CONSTRAINT FK_REGION_COUNTRY FOREIGN KEY (COUNTRY_CD) REFERENCES LKP_COUNTRY(COUNTRY_CD)
);

CREATE TABLE LKP_CITY (
    CITY_ID       NUMBER        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CITY_NM       VARCHAR2(200) NOT NULL,
    POSTAL_CD     VARCHAR2(20),
    REGION_CD     VARCHAR2(10),
    LAT           NUMBER(10,6),
    LNG           NUMBER(10,6),
    CONSTRAINT FK_CITY_REGION FOREIGN KEY (REGION_CD) REFERENCES LKP_REGION(REGION_CD)
);

-- =============================================================================
-- TABLES LOOKUP — Produits
-- =============================================================================

CREATE TABLE LKP_PROD_LINE (
    PROD_LINE_CD  VARCHAR2(20)  NOT NULL,
    PROD_LINE_NM  VARCHAR2(200) NOT NULL,
    BUSINESS_UNIT VARCHAR2(100),
    CONSTRAINT PK_PROD_LINE PRIMARY KEY (PROD_LINE_CD)
);

CREATE TABLE LKP_PROD_FAM (
    FAMILY_CD     VARCHAR2(20)  NOT NULL,
    FAMILY_NM     VARCHAR2(200) NOT NULL,
    PROD_LINE_CD  VARCHAR2(20),
    RISK_CAT      VARCHAR2(50),
    IS_REGULATED  NUMBER(1)     DEFAULT 0,
    CONSTRAINT PK_PROD_FAM PRIMARY KEY (FAMILY_CD),
    CONSTRAINT FK_FAM_LINE FOREIGN KEY (PROD_LINE_CD) REFERENCES LKP_PROD_LINE(PROD_LINE_CD)
);

CREATE TABLE DIM_PRODUCT (
    PRODUCT_ID    VARCHAR2(50)  NOT NULL,
    PRODUCT_NM    VARCHAR2(300) NOT NULL,
    FAMILY_CD     VARCHAR2(20),
    ISIN_CD       VARCHAR2(12),
    CURRENCY_CD   VARCHAR2(3),
    MATURITY_DT   VARCHAR2(8),
    ACTIVE_FLG    NUMBER(1)     DEFAULT 1,
    LAST_UPD_DT   DATE          DEFAULT SYSDATE,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID)
);

-- =============================================================================
-- DIM CUSTOMER
-- =============================================================================

CREATE TABLE DIM_CUSTOMER (
    CUST_ID       VARCHAR2(50)  NOT NULL,
    CUST_NM       VARCHAR2(300) NOT NULL,
    CUST_TYPE     VARCHAR2(50),
    CITY_ID       NUMBER,
    SEGMENT       VARCHAR2(100),
    KYC_STATUS    VARCHAR2(20)  DEFAULT 'APPROVED',
    LAST_UPD_DT   DATE          DEFAULT SYSDATE,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUST_ID)
);

-- =============================================================================
-- FACT TABLE TRANSACTIONS
-- =============================================================================

CREATE TABLE FACT_TXN (
    TXN_ID        VARCHAR2(50)  NOT NULL,
    TXN_DT        VARCHAR2(8)   NOT NULL,
    CUST_ID       VARCHAR2(50)  NOT NULL,
    PROD_ID       VARCHAR2(50)  NOT NULL,
    TXN_TYPE_CD   VARCHAR2(10),
    STATUS_CD     VARCHAR2(20),
    CHANNEL_CD    VARCHAR2(20),
    GROSS_AMT     NUMBER(18,4),
    NET_AMT       NUMBER(18,4),
    FEE_AMT       NUMBER(18,4)  DEFAULT 0,
    TAX_AMT       NUMBER(18,4)  DEFAULT 0,
    QTY           NUMBER(18,6),
    UNIT_PRICE    NUMBER(18,6),
    CURRENCY_CD   VARCHAR2(3),
    FX_RATE_EUR   NUMBER(10,6)  DEFAULT 1,
    LAST_UPD_DT   DATE          DEFAULT SYSDATE,
    CONSTRAINT PK_FACT_TXN PRIMARY KEY (TXN_ID)
);

-- Index pour optimiser les lectures JDBC partitionnées
CREATE INDEX IDX_FACT_TXN_DT ON FACT_TXN (LAST_UPD_DT);

-- =============================================================================
-- DONNÉES DE TEST
-- =============================================================================

-- Continents
INSERT INTO LKP_CONTINENT VALUES ('EU', 'Europe');
INSERT INTO LKP_CONTINENT VALUES ('AM', 'Amérique');
INSERT INTO LKP_CONTINENT VALUES ('AS', 'Asie');

-- Pays
INSERT INTO LKP_COUNTRY VALUES ('FRA', 'France',        'EU', 'EUR', 1, 1);
INSERT INTO LKP_COUNTRY VALUES ('DEU', 'Allemagne',     'EU', 'EUR', 1, 1);
INSERT INTO LKP_COUNTRY VALUES ('GBR', 'Royaume-Uni',   'EU', 'GBP', 0, 1);
INSERT INTO LKP_COUNTRY VALUES ('USA', 'États-Unis',    'AM', 'USD', 0, 1);
INSERT INTO LKP_COUNTRY VALUES ('JPN', 'Japon',         'AS', 'JPY', 0, 1);

-- Régions
INSERT INTO LKP_REGION VALUES ('IDF', 'Île-de-France',  'FRA');
INSERT INTO LKP_REGION VALUES ('ARA', 'Auvergne-Rhône', 'FRA');
INSERT INTO LKP_REGION VALUES ('BAY', 'Bavière',        'DEU');
INSERT INTO LKP_REGION VALUES ('NYC', 'New York',       'USA');

-- Villes
INSERT INTO LKP_CITY (CITY_NM, POSTAL_CD, REGION_CD, LAT, LNG) VALUES ('Paris',    '75001', 'IDF', 48.8566, 2.3522);
INSERT INTO LKP_CITY (CITY_NM, POSTAL_CD, REGION_CD, LAT, LNG) VALUES ('Lyon',     '69001', 'ARA', 45.7640, 4.8357);
INSERT INTO LKP_CITY (CITY_NM, POSTAL_CD, REGION_CD, LAT, LNG) VALUES ('Munich',   '80331', 'BAY', 48.1351, 11.5820);
INSERT INTO LKP_CITY (CITY_NM, POSTAL_CD, REGION_CD, LAT, LNG) VALUES ('New York', '10001', 'NYC', 40.7128, -74.0060);

-- Lignes produit
INSERT INTO LKP_PROD_LINE VALUES ('EQUITIES',    'Actions',              'Markets');
INSERT INTO LKP_PROD_LINE VALUES ('FIXED_INC',   'Obligations',          'Markets');
INSERT INTO LKP_PROD_LINE VALUES ('DERIVATIVES',  'Produits dérivés',    'Markets');

-- Familles produit
INSERT INTO LKP_PROD_FAM VALUES ('EU_STOCKS',  'Actions européennes',    'EQUITIES',   'MEDIUM', 0);
INSERT INTO LKP_PROD_FAM VALUES ('GOVT_BONDS', 'Obligations d''État',    'FIXED_INC',  'LOW',    1);
INSERT INTO LKP_PROD_FAM VALUES ('OPTIONS',    'Options vanille',         'DERIVATIVES','HIGH',   1);

-- Produits
INSERT INTO DIM_PRODUCT VALUES ('PROD001', 'BNP Paribas SA',            'EU_STOCKS',  'FR0000131104', 'EUR', '99991231', 1, SYSDATE);
INSERT INTO DIM_PRODUCT VALUES ('PROD002', 'OAT France 2030',           'GOVT_BONDS', 'FR0013131877', 'EUR', '20300125', 1, SYSDATE);
INSERT INTO DIM_PRODUCT VALUES ('PROD003', 'Call EUR/USD Strike 1.10',  'OPTIONS',    NULL,           'USD', '20241215', 1, SYSDATE);
INSERT INTO DIM_PRODUCT VALUES ('PROD004', 'Siemens AG',                'EU_STOCKS',  'DE0007236101', 'EUR', '99991231', 1, SYSDATE);
INSERT INTO DIM_PRODUCT VALUES ('PROD005', 'Bund Allemagne 2029',       'GOVT_BONDS', 'DE0001102432', 'EUR', '20290815', 1, SYSDATE);

-- Clients
INSERT INTO DIM_CUSTOMER VALUES ('CUST001', 'Groupe Renault SA',       'CORPORATE',    1, 'LARGE_CORP', 'APPROVED', SYSDATE);
INSERT INTO DIM_CUSTOMER VALUES ('CUST002', 'Caisse des Dépôts',       'INSTITUTIONAL',1, 'SOVEREIGN',  'APPROVED', SYSDATE);
INSERT INTO DIM_CUSTOMER VALUES ('CUST003', 'Jean-Pierre Martin',      'RETAIL',       2, 'PREMIUM',    'APPROVED', SYSDATE);
INSERT INTO DIM_CUSTOMER VALUES ('CUST004', 'Allianz SE',              'INSTITUTIONAL',3, 'INSURANCE',  'APPROVED', SYSDATE);
INSERT INTO DIM_CUSTOMER VALUES ('CUST005', 'Goldman Sachs Intl',      'CORPORATE',    4, 'LARGE_CORP', 'APPROVED', SYSDATE);

-- Transactions (données réalistes)
INSERT INTO FACT_TXN VALUES ('TXN001','20240101','CUST001','PROD001','BUY', 'SETTLED','ONLINE', 110000.00, 100000.00, 10000.00, 0.00, 1000, 100.00, 'EUR', 1.000000, SYSDATE);
INSERT INTO FACT_TXN VALUES ('TXN002','20240102','CUST002','PROD002','BUY', 'SETTLED','BRANCH',  55000.00,  50000.00,  5000.00, 0.00, 50,  1000.00,'EUR', 1.000000, SYSDATE);
INSERT INTO FACT_TXN VALUES ('TXN003','20240103','CUST001','PROD003','BUY', 'PENDING','API',    238600.00, 220000.00, 18600.00, 0.00, 200, 1100.00,'USD', 1.080000, SYSDATE);
INSERT INTO FACT_TXN VALUES ('TXN004','20240104','CUST003','PROD001','SELL','SETTLED','ONLINE',  22000.00,  20000.00,  2000.00, 0.00, 200, 100.00, 'EUR', 1.000000, SYSDATE);
INSERT INTO FACT_TXN VALUES ('TXN005','20240105','CUST004','PROD005','BUY', 'SETTLED','API',    515000.00, 500000.00, 15000.00, 0.00, 500, 1000.00,'EUR', 1.000000, SYSDATE);
INSERT INTO FACT_TXN VALUES ('TXN006','20240106','CUST005','PROD004','BUY', 'SETTLED','API',    164000.00, 160000.00,  4000.00, 0.00, 800, 200.00, 'EUR', 1.000000, SYSDATE);
INSERT INTO FACT_TXN VALUES ('TXN007','20240107','CUST002','PROD002','SELL','SETTLED','BRANCH',  30500.00,  30000.00,   500.00, 0.00, 30,  1000.00,'EUR', 1.000000, SYSDATE);
INSERT INTO FACT_TXN VALUES ('TXN008','20240108','CUST001','PROD005','BUY', 'SETTLED','ONLINE', 206000.00, 200000.00,  6000.00, 0.00, 200, 1000.00,'EUR', 1.000000, SYSDATE);
INSERT INTO FACT_TXN VALUES ('TXN009','20240109','CUST003','PROD001','BUY', 'CANCELLED','API',  11000.00,  10000.00,  1000.00, 0.00, 100, 100.00, 'EUR', 1.000000, SYSDATE);
INSERT INTO FACT_TXN VALUES ('TXN010','20240110','CUST004','PROD003','SELL','SETTLED','BRANCH', 108000.00, 100000.00,  8000.00, 0.00, 100, 1000.00,'USD', 1.080000, SYSDATE);

COMMIT;

-- Vérifications
SELECT 'LKP_CONTINENT' AS TABLE_NM, COUNT(*) AS CNT FROM LKP_CONTINENT
UNION ALL SELECT 'LKP_COUNTRY',   COUNT(*) FROM LKP_COUNTRY
UNION ALL SELECT 'LKP_REGION',    COUNT(*) FROM LKP_REGION
UNION ALL SELECT 'LKP_CITY',      COUNT(*) FROM LKP_CITY
UNION ALL SELECT 'LKP_PROD_LINE', COUNT(*) FROM LKP_PROD_LINE
UNION ALL SELECT 'LKP_PROD_FAM',  COUNT(*) FROM LKP_PROD_FAM
UNION ALL SELECT 'DIM_PRODUCT',   COUNT(*) FROM DIM_PRODUCT
UNION ALL SELECT 'DIM_CUSTOMER',  COUNT(*) FROM DIM_CUSTOMER
UNION ALL SELECT 'FACT_TXN',      COUNT(*) FROM FACT_TXN
ORDER BY 1;

PROMPT ✅ Setup Oracle terminé avec succès !
EXIT;
